[changelog]
header = """
# Changelog
"""
header = "# ğŸ‰ Whats new\n"
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/Amtrend/ssh-manager/commit/{{ commit.id }}))\
{% endfor %}
{% endfor %}
"""
footer = """
{% if previous.version %}
---
**Full changelog**: https://github.com/Amtrend/ssh-manager/compare/{{ previous.version }}...{{ version }}
{% endif %}
"""

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat", group = "ğŸš€ Features" },
  { message = "^fix", group = "ğŸ› Bug Fixes" },
  { message = "^docs", group = "ğŸ“ Documentation" },
  { message = "^chore", group = "ğŸ”§ Chores" },
  { message = ".*", group = "ğŸ“¦ Other Changes" }
]
